### ISSUE TITLE
    java.lang.UnsatisfiedLinkError: No implementation found for long jni.Predictor.createPredictorforCaffe(java.lang.String, java.lang.String) (tried Java_jni_Predictor_createPredictorforCaffe and Java_jni_Predictor_createPredictorforCaffe__Ljava_lang_String_2Ljava_lang_String_2)

### ISSUE THREAD

**Issue by winter1988** [zhangqianhui/CnnForAndroid#5]
06-22 14:36:05.544 26202-26202/com.example.tiny_cnn E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.tiny_cnn, PID: 26202
    java.lang.UnsatisfiedLinkError: No implementation found for long jni.Predictor.createPredictorforCaffe(java.lang.String, java.lang.String) (tried Java_jni_Predictor_createPredictorforCaffe and Java_jni_Predictor_createPredictorforCaffe__Ljava_lang_String_2Ljava_lang_String_2)
        at jni.Predictor.createPredictorforCaffe(Native Method)
        at jni.Predictor.<init>(Predictor.java:39)
        at com.example.tiny_cnn.SplashActivity$loadDataNati.handleMessage(SplashActivity.java:93)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:181)
        at android.app.ActivityThread.main(ActivityThread.java:6294)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:793)

**Comment by zhangqianhui** [comment]
No implementation found for long jni.Predictor.createPredictorforCaffe

**Comment by xwxu138** [comment]
run  app occur same exception
